version 1
AlexMAK1/java-shareit pull request #1
Opened 2022-08-20 13:15 UTC by AlexMAK1

version 1.0

2022-08-22 11:03 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +
в начале тела метода пустая строка не нужна

2022-08-22 11:05 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody ItemDto itemDto) {
хедер стоит вынести в константу

2022-08-22 11:51 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +
лишняя пустая строка

2022-08-22 11:52 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +
лишняя пустая строка

2022-08-22 11:52 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/UserConverter.java
> +    public UserDto userDto(User user) {
лучше назвать `toUserDto`

2022-08-22 11:52 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/UserConverter.java
> +    public User user(UserDto userDto) {
`toUser`

2022-08-22 11:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank
если аннотации в порядке увеличения длины, то такой код легче читать
```
@Email
@NotBlank
private String email;
```

2022-08-22 11:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    List<Item> itemList = new ArrayList<>();
нужно private и лучше сделать final 
название лучше `items`

2022-08-22 11:55 UTC, makholin requested changes
Нужно исправить замечания

2022-08-22 16:08 UTC, AlexMAK1 commented
Исправил замечания.

2022-08-23 09:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String HEADER = "X-Sharer-User-Id";
константы размещают в самом начале класса

2022-08-23 09:54 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String HEADER = "X-Sharer-User-Id";
и лучше назвать USER_ID_HEADER

2022-08-23 09:56 UTC, makholin approved these changes
Работа принята

2022-08-23 18:17 UTC, merged