version 1.0
AlexMAK1/java-shareit pull request #2
Opened 2022-09-07 22:58 UTC by AlexMAK1

version 1.0

2022-09-08 10:13 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingService bookingService;
константы и другие поля стоит разделять пустой строкой

2022-09-08 10:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            log.error("Вещь в данный момент не доступна");
в лог стоит добавить id вещи, которая недоступна

к остальным логам тоже стоит добавлять id объекта, о котором идет речь
это поможет быстрее и проще ориентироваться в большом количестве логов и находить нужные

2022-09-08 10:16 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingResponseDto update(Long id, Long userId, String approved) {
в контроллере лучше сразу распарсить строку approved и в сервис передавать уже boolean

2022-09-08 10:18 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved.equals("true")) {
в этих ифах код дублируется, можно упростить
```
booking.setStatus(approved ? APPROVED : REJECTED);
repository.save(booking);
log...
return ...
```

2022-09-08 10:19 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                "вещь не принаджит");
опечатка в слове

2022-09-08 10:20 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("FUTURE")) {
тоже можно убрать условия сначала распарсив статус из строки

`status = Status.valueOf(state) // можно вынести в отдельную функцию и в try catch там обернуть`

2022-09-08 10:22 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("FUTURE")) {
еще выглядит странно смешение двух сущностей state и status

2022-09-08 10:22 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingResponseDto> getOwnerBookings(String state, Long userId) {
метод очень большой, нужно сделать рефакторинг
подумать как убрать кучу if и возможно разделить на более маленькие методы

2022-09-08 10:23 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private Item item;
в дто классе поля по-хорошему тоже должны быть дто, иначе происходит смешение слоев приложения

2022-09-08 10:24 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +        // LocalDateTime start;
неиспользуемый код нужно удалить

2022-09-08 10:24 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +        Long id;
поля должны быть private

2022-09-08 10:26 UTC, makholin requested changes
Нужно исправить замечания

2022-09-08 23:29 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingService bookingService;
done

2022-09-08 23:29 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            log.error("Вещь в данный момент не доступна");
done

2022-09-08 23:29 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingResponseDto update(Long id, Long userId, String approved) {
done

2022-09-08 23:30 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved.equals("true")) {
done

2022-09-08 23:30 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                "вещь не принаджит");
done

2022-09-08 23:52 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("FUTURE")) {
Вот здесь не совсем понимаю, как это все в итоге должно выглядеть. 
Есть пример как это должно быть? 
Если сразу в контроллере пытаюсь распарсить в enum Status, тесты падают.

2022-09-08 23:58 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingResponseDto> getOwnerBookings(String state, Long userId) {
Кучу if можно заменить на кучу switch case, но особо по моему это не улучшит ситуацию. Разбить на отдельные методы можно, но как по мне так читать код проще, чем дергать экран вверх вниз. 
Либо как то по другому можно это отрефакторить?

2022-09-09 00:02 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +        // LocalDateTime start;
done

2022-09-09 00:02 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/item/dto/ItemInfoDto.java
> +        Long id;
done

2022-09-09 00:04 UTC, AlexMAK1 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    private Item item;
По ходу обучения данная практика не применялась, примеры которые приводят в теории и в коде так же имеют одинаковые поля. 
К примеру здесь можно посмотреть https://github.com/praktikum-java/module4_spring_without_boot/blob/repositories/src/main/java/ru/practicum/item/ItemDto.java

2022-09-09 10:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("FUTURE")) {
```
private Status parseStatus(String s) {
 try {
  return Status.valueOf(s);
  catch(InvArgExc e) {
    throw ValidationException(e.getMessage())
   }
}
```

2022-09-09 10:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.equals("FUTURE")) {
как то так сначала нужно получить статус

2022-09-09 10:14 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingResponseDto> getOwnerBookings(String state, Long userId) {
в отдельных методах ориентироваться легче, потому что в ide есть хоткеи для перехода в реализацию конретного метода вместо скролинга одного большого метода

2022-09-09 10:15 UTC, makholin requested changes
Нужно исправить оставшиеся замечания
Если возникнут вопросы, можно в слаке обсудить

2022-09-11 16:26 UTC, makholin approved these changes
Работа принята

2022-09-12 23:29 UTC, merged